name: CI for a new dev push

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    # Install pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel twine pytest

    # Execute tests
    - name: Execute pytest
      run: python -m pytest -o junit_family=xunit2 --doctest-modules --junitxml=junit/test-results.xml test/

    # Push test results
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: pytest-results
        path: junit/test-results.xml

    # Change dev version
    - name: Change version number
      run: |
        sed -i -e "s/__dev_version__/.dev$(date '+%y%m%d%H%M')/g" setup.py
        echo "::set-env=PACKAGE_VERSION="$(grep -oP "VERSION = \"\K\d\.\d[.ba\d]+\.dev\d{10}" setup.py)"

    # Build wheel and publish it
    - name: Build and publish to PyPI Test
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    # Push wheel as an artifact
    - name: Archive wheel
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    # Wait for the package to be ready
    - uses: nev7n/wait_for_response@v1
      with:
        url: 'https://test.pypi.org/SentiLeak/'${{PACKAGE_VERSION}}
        responseCode: 200
        timeout: 2000
        interval: 500

    # Check the package
    - name: Check the PyPI test package
      run: |
        pip uninstall -y -r requirements.txt
        rm -R sentileak
        pip install --extra-index-url https://test.pypi.org/simple/ SentiLeak==$PACKAGE_VERSION
        python -m pytest test/
